# Site settings
title: Things I Do
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "A blog, with blogging things"
baseurl: "/blog"
url: "http://mrandmrsphelan.com"
twitter_username: dtphelan
github_username:  dtphelan
facebook_username:  dan.phelan.14

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
