# Site settings
title: Things I Do
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "A blog, with blogging things"
baseurl: "/blog"
url: "http://mrandmrsphelan.com"
twitter_username: dtphelan
github_username:  dtphelan
facebook_username:  dan.phelan.14

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
highlighter: pygments
permalink: none
paginate: 5
pagination: true
plugins:  ./_plugins
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
