# Site settings
title: Things I Do
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "A blog, with blogging things"
baseurl: "/blog"
url: "http://mrandmrsphelan.com"
twitter_username: dtphelan
github_username:  dtphelan
facebook_username:  dan.phelan.14
collections:
  - reports

# Build settings
markdown: kramdown
kramdown:
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
highlighter: pygments
permalink: none
paginate: 5
plugins:  ./_plugins
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Travis CI settings
username: dtphelan
repo: blog
destination: ../dtphelan/blog-pages/
relative_source: ../dtphelan/blog/

# Prose.io settings
prose:
  ignore:
    - /_data
    - /_includes
    - /_layouts
    - /_plugins
    - /_site
    - /css
    - /fonts
    - /img
    - /js
    - /less
    - /mail
    - /node_modules
    - /report
    - .travis.yml
    - _config.yml
    - _config_dev.yml
    - about.html
    - feed.xml
    - Gruntfile.js
    - index.html
    - LICENSE
    - package.json
    - Rakefile
    - README.md
